#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChameleonForms.Generated
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using Microsoft.AspNetCore.Mvc.Razor;
    using ChameleonForms.Templates;
    using Microsoft.AspNetCore.Mvc.ModelBinding;

#line 3 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
    using ChameleonForms.Component.Config;
    
    #line default
    #line hidden
    
    #line 4 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
    using ChameleonForms.Templates.TwitterBootstrap3;
    
    #line default
    #line hidden
    
    #line 2 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
    using Microsoft.AspNetCore.Html;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public static class TwitterBootstrapHtmlHelpers
    {

public static HelperResult EndForm() {
return new HelperResult(async __razor_helper_writer => {



#line 8 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                   

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    </form>\r\n");



#line 10 "..\..\TwitterBootstrapHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static HelperResult BeginSection(IHtmlContent heading, IHtmlContent leadingHtml, HtmlAttributes htmlAttributes) {
return new HelperResult(async __razor_helper_writer => {



#line 12 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                     

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <fieldset");



#line 13 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, htmlAttributes);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, ">\r\n");



#line 14 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
    if (heading != null && !string.IsNullOrWhiteSpace(heading.ToString()))
    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <legend>");



#line 16 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, heading);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</legend>\r\n");



#line 17 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
    }
    if (leadingHtml != null && !string.IsNullOrWhiteSpace(leadingHtml.ToString()))
    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        ");



#line 20 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, leadingHtml);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



#line 21 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
    }
    
#line default
#line hidden

});

    }


public static HelperResult EndSection() {
return new HelperResult(async __razor_helper_writer => {



#line 24 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                          

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    </fieldset>\r\n");



#line 26 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
    
#line default
#line hidden

});

    }


public static HelperResult BeginNestedSection(IHtmlContent heading, IHtmlContent leadingHtml, HtmlAttributes htmlAttributes)
    {
return new HelperResult(async __razor_helper_writer => {



#line 29 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
     
    htmlAttributes.AddClass("panel panel-default");

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <div");



#line 31 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, htmlAttributes);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, ">\r\n");



#line 32 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
        if (heading != null && !string.IsNullOrWhiteSpace(heading.ToString()))
        {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <div class=\"panel-heading\">");



#line 34 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
  WebViewPage.WriteTo(@__razor_helper_writer, heading);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</div>\r\n");



#line 35 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
        }


#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <div class=\"panel-body\">\r\n");



#line 38 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
            if (leadingHtml != null && !string.IsNullOrWhiteSpace(leadingHtml.ToString()))
            {
            
#line default
#line hidden


#line 40 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, leadingHtml);

#line default
#line hidden


#line 40 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                        
            }
            
#line default
#line hidden

});

            }


public static HelperResult EndNestedSection() {
return new HelperResult(async __razor_helper_writer => {



#line 44 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                        

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        </div>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    </div>\r\n");



#line 48 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
        
#line default
#line hidden

});

        }


public static HelperResult BeginField(IHtmlContent labelHtml, IHtmlContent elementHtml, IHtmlContent validationHtml, ModelMetadata fieldMetadata, IReadonlyFieldConfiguration fieldConfiguration, bool isValid, IHtmlContent requiredDesignator) {
return new HelperResult(async __razor_helper_writer => {



#line 50 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                                                                                                                                                       
        
#line default
#line hidden


#line 51 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, BeginFieldInternal(labelHtml, elementHtml, validationHtml, fieldConfiguration, fieldMetadata, isValid, requiredDesignator));

#line default
#line hidden


#line 51 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                                                   

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <div class=\"row nested-fields\">\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <div class=\"col-xs-1\"></div>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <div class=\"col-xs-11\">\r\n");



#line 55 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                
#line default
#line hidden

});

                }


public static HelperResult EndField() {
return new HelperResult(async __razor_helper_writer => {



#line 57 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                    

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            </div>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        </div>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        </div>\r\n");



#line 63 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
        
#line default
#line hidden

});

        }


public static HelperResult GetInputGroupHtml(IHtmlContent html, bool isInputGroup) {
return new HelperResult(async __razor_helper_writer => {



#line 65 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                         
        
#line default
#line hidden


#line 66 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, new HtmlString(isInputGroup ? "<div class=\"input-group-addon\">" : ""));

#line default
#line hidden


#line 66 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                    
#line default
#line hidden


#line 66 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                         WebViewPage.WriteTo(@__razor_helper_writer, html);

#line default
#line hidden


#line 66 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                         
#line default
#line hidden


#line 66 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                               WebViewPage.WriteTo(@__razor_helper_writer, new HtmlString(isInputGroup ? "</div>" : ""));

#line default
#line hidden


#line 66 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                                                          
        
#line default
#line hidden

});

        }


public static HelperResult GetPrependedHtml(IReadonlyFieldConfiguration fieldConfiguration, bool isInputGroup) {
return new HelperResult(async __razor_helper_writer => {



#line 69 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                     
        foreach (var html in fieldConfiguration.PrependedHtml) {
#line default
#line hidden


#line 70 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                     WebViewPage.WriteTo(@__razor_helper_writer, GetInputGroupHtml(html, isInputGroup));

#line default
#line hidden


#line 70 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                      }
        
#line default
#line hidden

});

        }


public static HelperResult GetAppendedHtml(IReadonlyFieldConfiguration fieldConfiguration, bool isInputGroup) {
return new HelperResult(async __razor_helper_writer => {



#line 73 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                    
        foreach (var html in fieldConfiguration.AppendedHtml) {
#line default
#line hidden


#line 74 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                    WebViewPage.WriteTo(@__razor_helper_writer, GetInputGroupHtml(html, isInputGroup));

#line default
#line hidden


#line 74 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                     }
        
#line default
#line hidden

});

        }


public static HelperResult GetHint(IReadonlyFieldConfiguration fieldConfiguration) {
return new HelperResult(async __razor_helper_writer => {



#line 77 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                         
        if (fieldConfiguration.Hint != null) {
#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "<div class=\"help-block form-hint\">");



#line 78 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                     WebViewPage.WriteTo(@__razor_helper_writer, fieldConfiguration.Hint);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</div>");



#line 78 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                              }
        
#line default
#line hidden

});

        }


public static HelperResult GetPostElementRequiredDesignator(bool isRequired, bool displayDesignator, IHtmlContent requiredDesignator) {
return new HelperResult(async __razor_helper_writer => {



#line 81 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                                            
        if (!isRequired) { return; }
        if (displayDesignator) {
#line default
#line hidden


#line 83 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, requiredDesignator);

#line default
#line hidden


#line 83 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                   }
        
#line default
#line hidden

});

        }


public static HelperResult GetInputGroupRequiredDesignator(bool isRequired, bool isInputGroup, IHtmlContent requiredDesignator) {
return new HelperResult(async __razor_helper_writer => {



#line 86 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                                      
        if (!isRequired) { return; }
        if (isInputGroup) {
#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "<div class=\"input-group-addon required\">");



#line 88 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                        WebViewPage.WriteTo(@__razor_helper_writer, requiredDesignator);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</div>");



#line 88 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                            }
        
#line default
#line hidden

});

        }


public static HelperResult RequiredDesignator(IReadonlyFieldConfiguration fieldConfiguration) {
return new HelperResult(async __razor_helper_writer => {



#line 91 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                    

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <em class=\"required\" title=\"Required\">&lowast;</em>\r\n");



#line 93 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
        
#line default
#line hidden

});

        }


public static HelperResult GetLabelHtml(IHtmlContent labelHtml, bool hasLabel, bool isCheckboxControl, bool displayDesignator, bool isRequired, IHtmlContent requiredDesignator) {
return new HelperResult(async __razor_helper_writer => {



#line 95 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                                                                                       
        var wrapLabel = !hasLabel && !isCheckboxControl;
        if (wrapLabel) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "<span class=\"control-label\">\r\n");



#line 99 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
            }
            
#line default
#line hidden


#line 100 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, labelHtml);

#line default
#line hidden


#line 100 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                      
            if (displayDesignator && isRequired) {
            
#line default
#line hidden


#line 102 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, requiredDesignator);

#line default
#line hidden


#line 102 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                               
            }
            if (wrapLabel) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        </span>\r\n");



#line 107 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
        }
        
#line default
#line hidden

});

        }


public static HelperResult BeginFieldInternal(IHtmlContent labelHtml, IHtmlContent elementHtml, IHtmlContent validationHtml, IReadonlyFieldConfiguration fieldConfiguration, ModelMetadata fieldMetadata, bool isValid, IHtmlContent requiredDesignator) {
return new HelperResult(async __razor_helper_writer => {



#line 110 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                                                                                                                                                               
        var isCheckboxControl = fieldConfiguration.GetBagData<bool>
            ("IsCheckboxControl");
            var canBeInputGroup = fieldConfiguration.GetBagData<bool>
                ("CanBeInputGroup");
                var isRadioOrCheckboxList = fieldConfiguration.GetBagData<bool>
                    ("IsRadioOrCheckboxList");
                    var isRequired = fieldMetadata != null && fieldMetadata.IsRequired;
                    var isInputGroup = canBeInputGroup && (isRequired || fieldConfiguration.GetBagData<bool>
                        ("DisplayAsInputGroup"));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                        ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <div class=\"");



#line 120 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
        WebViewPage.WriteTo(@__razor_helper_writer, isCheckboxControl ? "checkbox" : "form-group");

#line default
#line hidden



#line 120 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                        WebViewPage.WriteTo(@__razor_helper_writer, !isValid ? " has-error" : string.Empty);

#line default
#line hidden



#line 120 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                 WebViewPage.WriteTo(@__razor_helper_writer, RenderIfNotEmpty(fieldConfiguration.FieldContainerClasses,item => new HelperResult(async __razor_template_writer => {

#line default
#line hidden


WebViewPage.WriteLiteralTo(@__razor_template_writer, " ");



#line 120 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                                                                                  WebViewPage.WriteTo(@__razor_template_writer, fieldConfiguration.FieldContainerClasses);

#line default
#line hidden



#line 120 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                                                                                                                                                                             })));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n");



#line 121 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                            
#line default
#line hidden


#line 121 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, GetLabelHtml(labelHtml, fieldConfiguration.HasLabelElement, isCheckboxControl, isRadioOrCheckboxList || (!isCheckboxControl && !isInputGroup), isRequired, requiredDesignator));

#line default
#line hidden


#line 121 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                                                                                                                           
                            if (isInputGroup)
                            {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                            ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <div class=\"input-group\">\r\n");



#line 125 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                                ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            ");



#line 126 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
   WebViewPage.WriteTo(@__razor_helper_writer, GetPrependedHtml(fieldConfiguration, isInputGroup));

#line default
#line hidden



#line 126 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                      WebViewPage.WriteTo(@__razor_helper_writer, elementHtml);

#line default
#line hidden



#line 126 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                  WebViewPage.WriteTo(@__razor_helper_writer, GetPostElementRequiredDesignator(isRequired, isCheckboxControl, requiredDesignator));

#line default
#line hidden



#line 126 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                                                                      WebViewPage.WriteTo(@__razor_helper_writer, GetAppendedHtml(fieldConfiguration, isInputGroup));

#line default
#line hidden



#line 126 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                                                                                                                        WebViewPage.WriteTo(@__razor_helper_writer, GetInputGroupRequiredDesignator(isRequired, isInputGroup, requiredDesignator));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



#line 127 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                if (isInputGroup)
                                {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                                ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                            </div>\r\n");



#line 131 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                            }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                            ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            ");



#line 132 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, GetHint(fieldConfiguration));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " ");



#line 132 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                            WebViewPage.WriteTo(@__razor_helper_writer, validationHtml);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



#line 133 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                            
#line default
#line hidden

});

                            }


public static HelperResult Field(IHtmlContent labelHtml, IHtmlContent elementHtml, IHtmlContent validationHtml, ModelMetadata fieldMetadata, IReadonlyFieldConfiguration fieldConfiguration, bool isValid, IHtmlContent requiredDesignator) {
return new HelperResult(async __razor_helper_writer => {



#line 135 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                                                                                                                                                                      
                            
#line default
#line hidden


#line 136 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, BeginFieldInternal(labelHtml, elementHtml, validationHtml, fieldConfiguration, fieldMetadata, isValid, requiredDesignator));

#line default
#line hidden


#line 136 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                                                                       

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                            ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                        </div>\r\n");



#line 139 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                        
#line default
#line hidden

});

                        }


public static HelperResult BeginMessage(EmphasisStyle messageType, IHtmlContent heading, bool emptyHeading) {
return new HelperResult(async __razor_helper_writer => {



#line 141 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                               

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                        ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "      <div class=\"panel ");



#line 142 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
       WebViewPage.WriteTo(@__razor_helper_writer, string.Format("panel-{0}", messageType.ToString().ToLower()));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n");



#line 143 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                            if (!emptyHeading)
                            {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                            ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "          <div class=\"panel-heading\"><h4 class=\"panel-title\">");



#line 145 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                WebViewPage.WriteTo(@__razor_helper_writer, heading);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</h4></div>\r\n");



#line 146 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                            }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                            ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "          <div class=\"panel-body\">\r\n");



#line 148 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                
#line default
#line hidden

});

                                }


public static HelperResult EndMessage() {
return new HelperResult(async __razor_helper_writer => {



#line 150 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                      

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                                ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                            </div>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                            ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                        </div>\r\n");



#line 155 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                        
#line default
#line hidden

});

                        }


public static HelperResult BeginNavigation() {
return new HelperResult(async __razor_helper_writer => {



#line 157 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                   

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                        ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <div class=\"btn-group\">\r\n");



#line 159 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                            
#line default
#line hidden

});

                            }


public static HelperResult EndNavigation() {
return new HelperResult(async __razor_helper_writer => {



#line 161 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                     

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                            ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                        </div>\r\n");



#line 164 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                        
#line default
#line hidden

});

                        }


public static HelperResult RadioOrCheckboxList(IEnumerable<IHtmlContent>
                            items, bool isCheckbox) {
return new HelperResult(async __razor_helper_writer => {



#line 167 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                     
                            foreach (var item in items) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                            <div class=\"");



#line 169 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, isCheckbox ? "checkbox" : "radio");

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">");



#line 169 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                   WebViewPage.WriteTo(@__razor_helper_writer, item);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</div>\r\n");



#line 170 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                            }
                            
#line default
#line hidden

});

                            }


public static HelperResult RenderIfNotEmpty(string mayBeEmpty, Func<object, IHtmlContent>
                                template) {
return new HelperResult(async __razor_helper_writer => {



#line 175 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                           
                                if (!string.IsNullOrEmpty(mayBeEmpty)) {
#line default
#line hidden


#line 176 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                             WebViewPage.WriteTo(@__razor_helper_writer, template(null));

#line default
#line hidden


#line 176 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                       }
                                
#line default
#line hidden

});

                                }


    }
}
#pragma warning restore 1591
