#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChameleonForms.Generated
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
    using ChameleonForms.Component.Config;
    
    #line default
    #line hidden
    
    #line 5 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
    using ChameleonForms.Enums;
    
    #line default
    #line hidden
    
    #line 7 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
    using ChameleonForms.Templates;
    
    #line default
    #line hidden
    
    #line 2 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
    using Microsoft.AspNetCore.Html;
    
    #line default
    #line hidden
    
    #line 3 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
    using Microsoft.AspNetCore.Mvc.ModelBinding;
    
    #line default
    #line hidden
    
    #line 6 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
    using Microsoft.AspNetCore.Mvc.Razor;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public static class TwitterBootstrapHtmlHelpers
    {

public static System.Web.WebPages.HelperResult EndForm() {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 11 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                   

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    </form>\r\n");



#line 13 "..\..\TwitterBootstrapHtmlHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult BeginSection(IHtmlContent heading, IHtmlContent leadingHtml, HtmlAttributes htmlAttributes) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 15 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                     

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <fieldset");



#line 16 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, htmlAttributes);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, ">\r\n");



#line 17 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
    if (heading != null && !string.IsNullOrWhiteSpace(heading.ToString()))
    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <legend>");



#line 19 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, heading);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</legend>\r\n");



#line 20 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
    }
    if (leadingHtml != null && !string.IsNullOrWhiteSpace(leadingHtml.ToString()))
    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        ");



#line 23 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, leadingHtml);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



#line 24 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
    }
    
#line default
#line hidden

});

    }


public static System.Web.WebPages.HelperResult EndSection() {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 27 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                          

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    </fieldset>\r\n");



#line 29 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
    
#line default
#line hidden

});

    }


public static System.Web.WebPages.HelperResult BeginNestedSection(IHtmlContent heading, IHtmlContent leadingHtml, HtmlAttributes htmlAttributes)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 32 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
     
    htmlAttributes.AddClass("panel panel-default");

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <div");



#line 34 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, htmlAttributes);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, ">\r\n");



#line 35 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
        if (heading != null && !string.IsNullOrWhiteSpace(heading.ToString()))
        {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <div class=\"panel-heading\">");



#line 37 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
  WebViewPage.WriteTo(@__razor_helper_writer, heading);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</div>\r\n");



#line 38 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
        }


#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <div class=\"panel-body\">\r\n");



#line 41 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
            if (leadingHtml != null && !string.IsNullOrWhiteSpace(leadingHtml.ToString()))
            {
            
#line default
#line hidden


#line 43 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, leadingHtml);

#line default
#line hidden


#line 43 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                        
            }
            
#line default
#line hidden

});

            }


public static System.Web.WebPages.HelperResult EndNestedSection() {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 47 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                        

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        </div>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    </div>\r\n");



#line 51 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
        
#line default
#line hidden

});

        }


public static System.Web.WebPages.HelperResult BeginField(IHtmlContent labelHtml, IHtmlContent elementHtml, IHtmlContent validationHtml, ModelMetadata fieldMetadata, IReadonlyFieldConfiguration fieldConfiguration, bool isValid, IHtmlContent requiredDesignator) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 53 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                                                                                                                                                       
        
#line default
#line hidden


#line 54 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, BeginFieldInternal(labelHtml, elementHtml, validationHtml, fieldConfiguration, fieldMetadata, isValid, requiredDesignator));

#line default
#line hidden


#line 54 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                                                   

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <div class=\"row nested-fields\">\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <div class=\"col-xs-1\"></div>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <div class=\"col-xs-11\">\r\n");



#line 58 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                
#line default
#line hidden

});

                }


public static System.Web.WebPages.HelperResult EndField() {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 60 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                    

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            </div>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        </div>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        </div>\r\n");



#line 66 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
        
#line default
#line hidden

});

        }


public static System.Web.WebPages.HelperResult GetInputGroupHtml(IHtmlContent html, bool isInputGroup) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 68 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                         
        
#line default
#line hidden


#line 69 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, new HtmlString(isInputGroup ? "<div class=\"input-group-addon\">" : ""));

#line default
#line hidden


#line 69 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                  
#line default
#line hidden


#line 69 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                       WebViewPage.WriteTo(@__razor_helper_writer, html);

#line default
#line hidden


#line 69 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                       
#line default
#line hidden


#line 69 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                             WebViewPage.WriteTo(@__razor_helper_writer, new HtmlString(isInputGroup ? "</div>" : ""));

#line default
#line hidden


#line 69 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                                                      
        
#line default
#line hidden

});

        }


public static System.Web.WebPages.HelperResult GetPrependedHtml(IReadonlyFieldConfiguration fieldConfiguration, bool isInputGroup) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 72 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                     
        foreach (var html in fieldConfiguration.PrependedHtml) {
#line default
#line hidden


#line 73 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                     WebViewPage.WriteTo(@__razor_helper_writer, GetInputGroupHtml(html, isInputGroup));

#line default
#line hidden


#line 73 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                      }
        
#line default
#line hidden

});

        }


public static System.Web.WebPages.HelperResult GetAppendedHtml(IReadonlyFieldConfiguration fieldConfiguration, bool isInputGroup) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 76 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                    
        foreach (var html in fieldConfiguration.AppendedHtml) {
#line default
#line hidden


#line 77 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                    WebViewPage.WriteTo(@__razor_helper_writer, GetInputGroupHtml(html, isInputGroup));

#line default
#line hidden


#line 77 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                     }
        
#line default
#line hidden

});

        }


public static System.Web.WebPages.HelperResult GetHint(IReadonlyFieldConfiguration fieldConfiguration) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 80 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                         
        if (fieldConfiguration.Hint != null) {
#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "<div class=\"help-block form-hint\">");



#line 81 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                     WebViewPage.WriteTo(@__razor_helper_writer, fieldConfiguration.Hint);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</div>");



#line 81 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                              }
        
#line default
#line hidden

});

        }


public static System.Web.WebPages.HelperResult GetPostElementRequiredDesignator(bool isRequired, bool displayDesignator, IHtmlContent requiredDesignator) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 84 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                                            
        if (!isRequired) { return; }
        if (displayDesignator) {
#line default
#line hidden


#line 86 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, requiredDesignator);

#line default
#line hidden


#line 86 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                   }
        
#line default
#line hidden

});

        }


public static System.Web.WebPages.HelperResult GetInputGroupRequiredDesignator(bool isRequired, bool isInputGroup, IHtmlContent requiredDesignator) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 89 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                                      
        if (!isRequired) { return; }
        if (isInputGroup) {
#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "<div class=\"input-group-addon required\">");



#line 91 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                        WebViewPage.WriteTo(@__razor_helper_writer, requiredDesignator);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</div>");



#line 91 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                            }
        
#line default
#line hidden

});

        }


public static System.Web.WebPages.HelperResult RequiredDesignator(IReadonlyFieldConfiguration fieldConfiguration) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 94 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                    

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <em class=\"required\" title=\"Required\">&lowast;</em>\r\n");



#line 96 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
        
#line default
#line hidden

});

        }


public static System.Web.WebPages.HelperResult GetLabelHtml(IHtmlContent labelHtml, bool hasLabel, bool isCheckboxControl, bool displayDesignator, bool isRequired, IHtmlContent requiredDesignator) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 98 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                                                                                       
        var wrapLabel = !hasLabel && !isCheckboxControl;
        if (wrapLabel) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "<span class=\"control-label\">\r\n");



#line 102 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
            }
            
#line default
#line hidden


#line 103 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, labelHtml);

#line default
#line hidden


#line 103 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                      
            if (displayDesignator && isRequired) {
            
#line default
#line hidden


#line 105 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, requiredDesignator);

#line default
#line hidden


#line 105 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                               
            }
            if (wrapLabel) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        </span>\r\n");



#line 110 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
        }
        
#line default
#line hidden

});

        }


public static System.Web.WebPages.HelperResult BeginFieldInternal(IHtmlContent labelHtml, IHtmlContent elementHtml, IHtmlContent validationHtml, IReadonlyFieldConfiguration fieldConfiguration, ModelMetadata fieldMetadata, bool isValid, IHtmlContent requiredDesignator) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 113 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                                                                                                                                                               
        var isCheckboxControl = fieldConfiguration.GetBagData<bool>
            ("IsCheckboxControl");
            var canBeInputGroup = fieldConfiguration.GetBagData<bool>
                ("CanBeInputGroup");
                var isRadioOrCheckboxList = fieldConfiguration.GetBagData<bool>
                    ("IsRadioOrCheckboxList");
                    var isRequired = fieldMetadata != null && fieldMetadata.IsRequired;
                    var isInputGroup = canBeInputGroup && (isRequired || fieldConfiguration.GetBagData<bool>
                        ("DisplayAsInputGroup"));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                        ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <div class=\"");



#line 123 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
        WebViewPage.WriteTo(@__razor_helper_writer, isCheckboxControl ? "checkbox" : "form-group");

#line default
#line hidden



#line 123 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                        WebViewPage.WriteTo(@__razor_helper_writer, !isValid ? " has-error" : string.Empty);

#line default
#line hidden



#line 123 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                 WebViewPage.WriteTo(@__razor_helper_writer, RenderIfNotEmpty(fieldConfiguration.FieldContainerClasses,item => new System.Web.WebPages.HelperResult(__razor_template_writer => {

#line default
#line hidden


WebViewPage.WriteLiteralTo(@__razor_template_writer, " ");



#line 123 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                                                                                  WebViewPage.WriteTo(@__razor_template_writer, fieldConfiguration.FieldContainerClasses);

#line default
#line hidden



#line 123 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                                                                                                                                                                             })));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n");



#line 124 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                            
#line default
#line hidden


#line 124 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, GetLabelHtml(labelHtml, fieldConfiguration.HasLabelElement, isCheckboxControl, isRadioOrCheckboxList || (!isCheckboxControl && !isInputGroup), isRequired, requiredDesignator));

#line default
#line hidden


#line 124 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                                                                                                                           
                            if (isInputGroup)
                            {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                            ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <div class=\"input-group\">\r\n");



#line 128 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                                ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            ");



#line 129 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
   WebViewPage.WriteTo(@__razor_helper_writer, GetPrependedHtml(fieldConfiguration, isInputGroup));

#line default
#line hidden



#line 129 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                      WebViewPage.WriteTo(@__razor_helper_writer, elementHtml);

#line default
#line hidden



#line 129 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                  WebViewPage.WriteTo(@__razor_helper_writer, GetPostElementRequiredDesignator(isRequired, isCheckboxControl, requiredDesignator));

#line default
#line hidden



#line 129 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                                                                      WebViewPage.WriteTo(@__razor_helper_writer, GetAppendedHtml(fieldConfiguration, isInputGroup));

#line default
#line hidden



#line 129 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                                                                                                                        WebViewPage.WriteTo(@__razor_helper_writer, GetInputGroupRequiredDesignator(isRequired, isInputGroup, requiredDesignator));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



#line 130 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                if (isInputGroup)
                                {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                                ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                            </div>\r\n");



#line 134 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                            }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                            ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            ");



#line 135 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, GetHint(fieldConfiguration));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " ");



#line 135 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                            WebViewPage.WriteTo(@__razor_helper_writer, validationHtml);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



#line 136 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                            
#line default
#line hidden

});

                            }


public static System.Web.WebPages.HelperResult Field(IHtmlContent labelHtml, IHtmlContent elementHtml, IHtmlContent validationHtml, ModelMetadata fieldMetadata, IReadonlyFieldConfiguration fieldConfiguration, bool isValid, IHtmlContent requiredDesignator) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 138 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                                                                                                                                                                      
                            
#line default
#line hidden


#line 139 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, BeginFieldInternal(labelHtml, elementHtml, validationHtml, fieldConfiguration, fieldMetadata, isValid, requiredDesignator));

#line default
#line hidden


#line 139 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                                                                                       

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                            ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                        </div>\r\n");



#line 142 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                        
#line default
#line hidden

});

                        }


public static System.Web.WebPages.HelperResult BeginMessage(EmphasisStyle messageType, IHtmlContent heading) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 144 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                               

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                        ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "      <div class=\"panel ");



#line 145 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
       WebViewPage.WriteTo(@__razor_helper_writer, string.Format("panel-{0}", messageType.ToString().ToLower()));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n");



#line 146 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                            if (!string.IsNullOrEmpty(heading.ToHtmlString()))
                            {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                            ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "          <div class=\"panel-heading\"><h4 class=\"panel-title\">");



#line 148 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                WebViewPage.WriteTo(@__razor_helper_writer, heading);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</h4></div>\r\n");



#line 149 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                            }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                            ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "          <div class=\"panel-body\">\r\n");



#line 151 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                
#line default
#line hidden

});

                                }


public static System.Web.WebPages.HelperResult EndMessage() {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 153 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                      

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                                ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                            </div>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                            ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                        </div>\r\n");



#line 158 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                        
#line default
#line hidden

});

                        }


public static System.Web.WebPages.HelperResult BeginNavigation() {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 160 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                   

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                        ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <div class=\"btn-group\">\r\n");



#line 162 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                            
#line default
#line hidden

});

                            }


public static System.Web.WebPages.HelperResult EndNavigation() {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 164 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                     

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                            ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                        </div>\r\n");



#line 167 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                        
#line default
#line hidden

});

                        }


public static System.Web.WebPages.HelperResult RadioOrCheckboxList(IEnumerable<IHtmlContent>
                            items, bool isCheckbox) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 170 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                     
                            foreach (var item in items) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                            <div class=\"");



#line 172 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, isCheckbox ? "checkbox" : "radio");

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">");



#line 172 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                   WebViewPage.WriteTo(@__razor_helper_writer, item);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</div>\r\n");



#line 173 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                            }
                            
#line default
#line hidden

});

                            }


public static System.Web.WebPages.HelperResult RenderIfNotEmpty(string mayBeEmpty, Func<object, IHtmlContent>
                                template) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 178 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                           
                                if (!string.IsNullOrEmpty(mayBeEmpty)) {
#line default
#line hidden


#line 179 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                             WebViewPage.WriteTo(@__razor_helper_writer, template(null));

#line default
#line hidden


#line 179 "..\..\TwitterBootstrapHtmlHelpers.cshtml"
                                                                                       }
                                
#line default
#line hidden

});

                                }


    }
}
#pragma warning restore 1591
